version: "3.5"

services:
  postgres:
    container_name: wakacop-postgres-final
    image: postgres:16-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata_v16:/var/lib/postgresql/data

  localstack:
    container_name: wakacop-localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=sns
      - DOCKER_HOST=unix:///var/run/docker.sock

    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      -
volumes:
  pgdata_v16:
